
version: "3.9"
services: 
  expressapp-dev:
    container_name: expressapp-dev
    build:
      context: ./api
      dockerfile: Dockerfile.dev-api
    expose: 
      - 5010
    volumes:
      - ./api:/usr/src/app
      - /root/OneDrive:/app/OneDrive

    restart: always  
  reactapp-dev:
    container_name: reactapp-dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev-client
    expose: 
      - 3010
    volumes:
      - ./client:/usr/src/app

    depends_on:
      - expressapp-dev
    environment:
      - REACT_APP_API_URL=http://expressapp:5010
    restart: always

  nginx-dev:
    build:
      context: ./nginx
      dockerfile: Dockerfile-dev-nginx
    ports:
      - 8081:81
    depends_on:
      - expressapp-dev
      - reactapp-dev
    restart: always

  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - certs:/etc/nginx/certs:ro
  #     - /var/www/pedia/.well-known/acme-challenge/test.txt
  #     - vhostd:/etc/nginx/vhost.d
  #     - html:/usr/share/nginx/html
  #     - acme:/etc/nginx/acme
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   labels:
  #     - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  # acme-companion:
  #   image: nginxproxy/acme-companion
  #   restart: always
  #   environment:
  #     - NGINX_PROXY_CONTAINER=nginx-proxy
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - certs:/etc/nginx/certs:rw
  #     - acme:/etc/acme.sh
  #     - vhostd:/etc/nginx/vhost.d
  #     - html:/usr/share/nginx/html
volumes:
  certs:
  html:
  vhostd:
  acme:
