version: "3.9"
services: 
    expressapp:
        container_name: expressapp
        build: ./api
        expose: 
            - 5000
        volumes:
            - ./api:/usr/src/app
    reactapp:
        container_name: reactapp
        build: ./client
        expose: 
            - 3000
        volumes:
            - ./client:/usr/src/app
    nginx:
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - expressapp
            - reactapp
            - nginx-proxy
            - acme-companion
            - db
        environment:
            - VIRTUAL_HOST=internal-naturalistone.com ,www.internal-naturalistone.com 
            - LETSENCRYPT_HOST=internal-naturalistone.com ,www.internal-naturalistone.com   
        restart: always
    nginx-proxy:
        image: jwilder/nginx-proxy
        restart: always
        ports:
            - "81:81"
            - "443:443"
        volumes:
            - certs:/etc/nginx/certs:ro
            - vhostd:/etc/nginx/vhost.docker
            - html:/usr/share/nginx/html
            - acme:/etc/acme.sh
            - /var/run/docker.sock:/tmp/docker.sock:ro
        labels:
            - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

    acme-companion:
        image: nginxproxy/acme-companion
        restart: always
        environment:
        - NGINX_PROXY_CONTAINER=nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - certs:/etc/nginx/certs:rw
            - acme:/etc/acme.sh
            - vhostd:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
    db:
        container_name: mysql
        image: mysql:latest
        command: --verbose --log-bin-index=/tmp/tmp.lm8Owcz5zs
        restart: unless-stopped
        expose:
            - "3306"
        volumes:
            - ./db:/var/lib/mysql
        environment:
            - DB_USER= admin
            - DB_PASSWORD= Ra7878782
            - DB_HOST= naturalistone.cfbecwildn3j.us-east-1.rds.amazonaws.com
            - DB_PORT= 3306
            - DB_TABLE= NaturaliStone
volumes:
    certs:
    html:
    vhostd:
    acme: